"""fixed foreign key in workouts

Revision ID: 3fd9590d2e38
Revises: 223b2c6777c1
Create Date: 2021-03-06 16:30:31.734071

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3fd9590d2e38'
down_revision = '223b2c6777c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exercises', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('exercises', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('workouts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('workouts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_foreign_key(None, 'workouts', 'users', ['created_by'], ['id'])
    op.add_column('workouts_exercises', sa.Column('created_at', sa.Date(), nullable=False))
    op.add_column('workouts_exercises', sa.Column('updated_at', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workouts_exercises', 'updated_at')
    op.drop_column('workouts_exercises', 'created_at')
    op.drop_constraint(None, 'workouts', type_='foreignkey')
    op.alter_column('workouts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('workouts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('exercises', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('exercises', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###
