"""id column for association object

Revision ID: 6a94fcb3196e
Revises: 3fd9590d2e38
Create Date: 2021-03-06 18:37:04.593082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a94fcb3196e'
down_revision = '3fd9590d2e38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workouts_exercises', sa.Column('id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'workouts_exercises', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workouts_exercises', type_='unique')
    op.drop_column('workouts_exercises', 'id')
    # ### end Alembic commands ###
