"""removed id column

Revision ID: 028547734401
Revises: 6a94fcb3196e
Create Date: 2021-03-06 18:46:14.646074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '028547734401'
down_revision = '6a94fcb3196e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('workouts_exercises_id_key', 'workouts_exercises', type_='unique')
    op.drop_column('workouts_exercises', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workouts_exercises', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_unique_constraint('workouts_exercises_id_key', 'workouts_exercises', ['id'])
    # ### end Alembic commands ###
